# enables container build on travis
sudo: false

language: java
jdk:
  - oraclejdk8

# some engines need java 7
addons:
  apt:
    packages:
    - openjdk-7-jre

env:
  - JAVA7_HOME=/usr/lib/jvm/java7-openjdk-amd64/jre

install:
  - TERM=dumb travis_retry ./gradlew assemble --info

script:
  - TERM=dumb ./gradlew check --info

after_success:
- ./gradlew jacocoTestReport coveralls
