# enables container build on travis
sudo: false

language: java
jdk:
  - oraclejdk8

# some engines need java 7
addons:
  apt:
    packages:
    - oracle-java7-installer

cache:
  directories:
  - downloads
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

env:
  - JAVA7_HOME=/usr/lib/jvm/java-7-oracle/jre/

install:
  - TERM=dumb travis_retry ./gradlew assemble --info --stacktrace

script:
  - TERM=dumb ./gradlew check --info --stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls
